server:
  port: 8080
  tomcat:
    max-threads: 800
    uri-encoding: UTF-8

spring:
  application:
    name: swagger2word
  thymeleaf:
    prefix: classpath:/templates/
    suffix: .html
    cache: false
    servlet:
      content-type: text/html
    enabled: true
    encoding: UTF-8
    mode: HTML5

# Swagger json url address
# etc. https://petstore.swagger.io/
swagger.url: http://10.5.4.242:8081/v1//v2/api-docs







